import type { TranslationKeys } from "./translations";

const ar: TranslationKeys = {
  nav: { solutions: "الحلول", demo: "تجربة", pricing: "الأسعار", caseStudies: "قصص النجاح", roiCalculator: "حاسبة العائد", dashboard: "لوحة التحكم", tryDemo: "جرّب العرض" },
  hero: { badge: "مدعوم بـ GPT-4 + ElevenLabs Voice AI", headline1: "خفّض تكاليف الدعم 70%", headline2: "مع ذكاء اصطناعي يتحدث فعلاً", subtitle: "روبوتات دردشة ووكلاء صوت ذكاء اصطناعي مخصصة تتولى خدمة العملاء وتأهيل العملاء المحتملين وحجز المواعيد — على مدار الساعة. مبني بـ Voiceflow و ElevenLabs و Twilio.", ctaVoice: "جرّب العرض الصوتي", ctaRoi: "احسب عائد الاستثمار", statBusinesses: "شركات مخدومة", statCost: "خفض التكاليف", statAvailability: "التوفر", statResponse: "وقت الاستجابة" },
  trust: { headline: "أكثر من 500 شركة حول العالم تثق بنا", soc2: "متوافق مع SOC 2", uptime: "اتفاقية 99.9% وقت تشغيل", hipaa: "جاهز لـ HIPAA" },
  solutions: { headline: "حلول الذكاء الاصطناعي", headlineAccent: "حسب القطاع", subtitle: "وكلاء ذكاء اصطناعي مصممون بمعرفة وسير عمل خاص بكل قطاع.", healthcare: "الرعاية الصحية", healthcareDesc: "أتمتة تفاعلات المرضى مع الحفاظ على امتثال HIPAA.", healthcareF1: "جدولة المواعيد", healthcareF2: "فرز المرضى", healthcareF3: "التحقق من التأمين", realEstate: "العقارات", realEstateDesc: "التقط كل عميل محتمل وجدولة العروض على مدار الساعة.", realEstateF1: "تأهيل العملاء المحتملين", realEstateF2: "معلومات العقارات", realEstateF3: "جدولة العروض", ecommerce: "التجارة الإلكترونية", ecommerceDesc: "دعم فوري يعزز الرضا ويقلل المرتجعات.", ecommerceF1: "تتبع الطلبات", ecommerceF2: "معالجة المرتجعات", ecommerceF3: "توصيات المنتجات", legal: "القانون", legalDesc: "تبسيط استقبال العملاء والإجابة على الأسئلة الشائعة فوراً.", legalF1: "نماذج الاستقبال", legalF2: "جدولة الاستشارات", legalF3: "إدارة الأسئلة الشائعة", homeServices: "خدمات المنزل", homeServicesDesc: "لن تفوتك مكالمة خدمة أو إرسال طوارئ مرة أخرى.", homeServicesF1: "إدارة الحجوزات", homeServicesF2: "تقديرات فورية", homeServicesF3: "إرسال الطوارئ", agencies: "الوكالات", agenciesDesc: "وكلاء ذكاء اصطناعي بعلامة بيضاء مخصصون لكل عميل من عملائك.", agenciesF1: "حل العلامة البيضاء", agenciesF2: "لوحة تحكم متعددة العملاء", agenciesF3: "تجارب مخصصة للعلامة التجارية", learnMore: "اعرف المزيد" },
  demo: { headline: "جرّب وكيل الذكاء الاصطناعي", headlineAccent: "مباشرة", subtitle: "تعرّف على Alex Rivera — أخصائي نجاح العملاء بالذكاء الاصطناعي. جرّب الصوت أو الدردشة.", voiceTitle: "تحدث مع Alex", alexName: "Alex Rivera", alexRole: "أخصائي نجاح العملاء بالذكاء الاصطناعي", speakersOn: "مكبرات الصوت مفعّلة • انقر للاتصال", callAlex: "اتصل بـ Alex", ringing: "جارٍ الاتصال...", connecting: "جارٍ التوصيل", speaking: "يتحدث...", listening: "يستمع...", endCall: "إنهاء المكالمة", cancel: "إلغاء", poweredVoice: "العرض يستخدم تركيب الصوت في المتصفح • الإنتاج يستخدم ElevenLabs Expressive v3", chatTitle: "تحدث مع Alex", chatPlaceholder: "اسأل Alex أي شيء...", chatHints: "جرّب: الأسعار، الصحة، العائد، تجربة، غير متأكد، محبط، كم من الوقت، النتائج", chatGreeting: "مرحباً! أنا Alex من VoiceFlow AI. سعيد جداً بزيارتك. كيف يمكنني مساعدتك اليوم؟" },
  pricing: { headline: "أسعار", headlineAccent: "بسيطة وشفافة", subtitle: "رسوم إعداد + شهري. بدون تكاليف مخفية. توسّع حسب نموك.", starter: "المبتدئ", starterAudience: "الشركات الصغيرة", professional: "المحترف", professionalAudience: "الشركات النامية", enterprise: "المؤسسات", enterpriseAudience: "المنظمات الكبيرة والوكالات", month: "/شهر", setupFee: "رسوم الإعداد", customPricing: "إعداد وأسعار مخصصة", mostPopular: "الأكثر شعبية", getStarted: "ابدأ الآن", startTrial: "تجربة مجانية", contactSales: "اتصل بالمبيعات", f_chatbot1: "روبوت دردشة واحد", f_convos500: "500 محادثة/شهر", f_emailSupport: "دعم بالبريد الإلكتروني", f_basicAnalytics: "تحليلات أساسية", f_voiceflow: "تكامل Voiceflow", f_lang1: "لغة واحدة", f_chatVoice: "روبوت دردشة + وكيل صوتي", f_convos2500: "2,500 محادثة/شهر", f_prioritySupport: "دعم ذو أولوية", f_advancedAnalytics: "تحليلات متقدمة", f_fullStack: "Voiceflow + Twilio + ElevenLabs", f_lang5: "5 لغات", f_crm: "تكامل CRM", f_leadQual: "تأهيل العملاء المحتملين", f_unlimitedAgents: "وكلاء غير محدودين", f_unlimitedConvos: "محادثات غير محدودة", f_dedicatedManager: "مدير حساب مخصص", f_customIntegrations: "تكاملات مخصصة", f_whiteLabel: "خيار العلامة البيضاء", f_allLangs: "جميع اللغات", f_sla: "ضمان SLA", f_customTraining: "تدريب ذكاء اصطناعي مخصص" },
  caseStudies: { headline: "نتائج حقيقية من", headlineAccent: "شركات حقيقية", subtitle: "اكتشف كيف توفر شركات مثل شركتك آلاف الدولارات مع خدمة العملاء بالذكاء الاصطناعي.", challenge: "التحدي:", solution: "الحل:", med: { name: "عيادة MedFirst", industry: "الرعاية الصحية", challenge: "أكثر من 200 مكالمة مريض يومياً تثقل كاهل فريق من 3 أشخاص", solution: "وكيل صوتي بالذكاء الاصطناعي لجدولة المواعيد وفرز المرضى", m1: "73%", m1l: "تحويل المكالمات", m2: "45%", m2l: "تقليل عدم الحضور", m3: "$12,400", m3l: "وفورات شهرية", m4: "4.8/5", m4l: "رضا المرضى", quote: "حوّل VoiceFlow AI عمليات الاستقبال لدينا. يحب المرضى الحجز الفوري، وأصبح بإمكان فريقنا أخيراً التركيز على الرعاية الشخصية.", person: "د. سارة تشن، المديرة الطبية" }, apex: { name: "مجموعة Apex العقارية", industry: "العقارات", challenge: "فقدان 60% من العملاء المحتملين خارج ساعات العمل بدون نظام متابعة", solution: "روبوت دردشة + وكيل صوتي لتأهيل العملاء على مدار الساعة", m1: "340%", m1l: "عملاء محتملون مؤهلون أكثر", m2: "28%", m2l: "استجابة أسرع", m3: "$31,000", m3l: "إيرادات شهرية جديدة", m4: "89%", m4l: "معدل التقاط العملاء", quote: "انتقلنا من فقدان معظم الاستفسارات خارج ساعات العمل إلى التقاط كل عميل محتمل تقريباً. كان العائد واضحاً في الشهر الأول.", person: "ماركوس جونسون، وسيط/مالك" }, shop: { name: "ShopWave", industry: "التجارة الإلكترونية", challenge: "متوسط وقت الاستجابة 8 ساعات يبعد العملاء", solution: "روبوت دردشة يتعامل مع الطلبات والمرتجعات وأسئلة المنتجات", m1: "ثانيتان", m1l: "وقت الاستجابة", m2: "82%", m2l: "حل تلقائي", m3: "$18,700", m3l: "وفورات شهرية", m4: "92%", m4l: "رضا العملاء", quote: "كان عملاؤنا ينتظرون ساعات للحصول على رد. الآن يحصلون على مساعدة فورية ودقيقة على مدار الساعة. انخفضت تذاكر الدعم بشكل كبير.", person: "ليزا بارك، رئيسة تجربة العملاء" } },
  roi: { headline: "احسب", headlineAccent: "عائد الاستثمار", subtitle: "اكتشف بالضبط كم يمكنك توفيره مع VoiceFlow AI.", tickets: "تذاكر الدعم الشهرية", costPerTicket: "متوسط تكلفة التذكرة", agents: "وكلاء الدعم الحاليون", salary: "متوسط راتب الوكيل", yr: "/سنة", resultsTitle: "وفوراتك المتوقعة", currentCost: "التكلفة الشهرية الحالية", aiHandled: "نسبة المعالجة بالذكاء الاصطناعي", monthlySavings: "الوفورات الشهرية", annualSavings: "الوفورات السنوية", paysItself: "يسترد تكلفته في", month_one: "شهر", months: "أشهر", getQuote: "احصل على عرض سعر مخصص" },
  dashboard: { headline: "مركز", headlineAccent: "القيادة", subtitle: "راقب كل محادثة وتتبع الأداء وحسّن وكلاء الذكاء الاصطناعي من لوحة تحكم واحدة.", title: "لوحة تحكم VoiceFlow AI", overview: "نظرة عامة", conversations: "المحادثات", agentsNav: "الوكلاء", analytics: "التحليلات", settings: "الإعدادات", totalConvos: "إجمالي المحادثات", resolutionRate: "معدل الحل", avgResponse: "متوسط الاستجابة", customerSat: "رضا العملاء", chartTitle: "حجم المحادثات (7 أيام)", recentTitle: "المحادثات الأخيرة", resolved: "محلول", inProgress: "قيد التنفيذ", escalated: "مصعّد", getAccess: "احصل على وصول كامل للوحة التحكم" },
  quote: { headline: "احصل على", headlineAccent: "عرض سعر فوري بالذكاء الاصطناعي", subtitle: "أجب عن بعض الأسئلة وسيوصي ذكاؤنا الاصطناعي بالحل المثالي.", step1: "ما هو قطاعك؟", step2: "كم عدد تفاعلات العملاء شهرياً؟", step3: "ما القنوات التي تحتاجها؟", step4: "أوشكت على الانتهاء! أخبرنا عنك.", vol1: "أقل من 500", vol2: "500 - 2,000", vol3: "2,000 - 5,000", vol4: "5,000+", chWebsite: "دردشة الموقع", chPhone: "هاتف/صوت", chSMS: "SMS", chWhatsApp: "WhatsApp", chSocial: "وسائل التواصل الاجتماعي", nameField: "الاسم الكامل", emailField: "البريد الإلكتروني", phoneField: "رقم الهاتف", companyField: "اسم الشركة", back: "رجوع", next: "التالي", getMyQuote: "احصل على عرض السعر", quoteReady: "عرض السعر جاهز!", basedOn: "بناءً على إجاباتك، نوصي بـ:", plan: "الخطة", forIndustry: "لـ", withVolume: "مع", monthlyInteractions: "تفاعل شهري", estSavings: "الوفورات الشهرية المقدرة", specialistContact: "سيتواصل معك أخصائي خلال ساعتين على", other: "أخرى" },
  footer: { tagline: "خدمة عملاء بالذكاء الاصطناعي لا تنام أبداً.", solutions: "الحلول", company: "الشركة", resources: "الموارد", about: "من نحن", careers: "وظائف", blog: "المدونة", contact: "اتصل بنا", partners: "الشركاء", docs: "التوثيق", apiRef: "مرجع API", status: "حالة الخدمة", privacy: "سياسة الخصوصية", terms: "شروط الخدمة", copyright: "© 2024 VoiceFlow AI. جميع الحقوق محفوظة.", builtWith: "مبني بـ Voiceflow + ElevenLabs + Twilio" },
  langName: "العربية",
};

export default ar;
