import type { TranslationKeys } from "./translations";

const ja: TranslationKeys = {
  nav: { solutions: "ソリューション", demo: "デモ", pricing: "料金", caseStudies: "導入事例", roiCalculator: "ROI計算", dashboard: "ダッシュボード", tryDemo: "デモを試す" },
  hero: { badge: "GPT-4 + ElevenLabs Voice AI搭載", headline1: "サポートコストを70%削減", headline2: "実際に話すAIで", subtitle: "カスタムAIチャットボットと音声エージェントが、カスタマーサービス、リード獲得、予約管理を24時間365日対応。Voiceflow、ElevenLabs、Twilioで構築。", ctaVoice: "音声デモを試す", ctaRoi: "ROIを計算する", statBusinesses: "導入企業数", statCost: "コスト削減", statAvailability: "稼働率", statResponse: "応答時間" },
  trust: { headline: "世界500社以上の企業に信頼されています", soc2: "SOC 2準拠", uptime: "99.9%稼働率SLA", hipaa: "HIPAA対応" },
  solutions: { headline: "AIソリューション", headlineAccent: "業界別", subtitle: "業界固有の知識とワークフローに特化したAIエージェント。", healthcare: "医療", healthcareDesc: "HIPAA準拠を維持しながら患者対応を自動化。", healthcareF1: "予約スケジューリング", healthcareF2: "患者トリアージ", healthcareF3: "保険確認", realEstate: "不動産", realEstateDesc: "すべてのリードを獲得し、24時間内覧を手配。", realEstateF1: "リード評価", realEstateF2: "物件情報", realEstateF3: "内覧スケジューリング", ecommerce: "Eコマース", ecommerceDesc: "顧客満足度を向上させ、返品を削減する即時サポート。", ecommerceF1: "注文追跡", ecommerceF2: "返品処理", ecommerceF3: "商品レコメンド", legal: "法律", legalDesc: "クライアント受付を効率化し、よくある質問に即座に回答。", legalF1: "受付フォーム", legalF2: "相談予約", legalF3: "FAQ対応", homeServices: "ホームサービス", homeServicesDesc: "サービスコールや緊急出動を二度と見逃しません。", homeServicesF1: "予約管理", homeServicesF2: "即時見積もり", homeServicesF3: "緊急ディスパッチ", agencies: "代理店", agenciesDesc: "各クライアント向けにブランド化されたホワイトラベルAIエージェント。", agenciesF1: "ホワイトラベルソリューション", agenciesF2: "マルチクライアントダッシュボード", agenciesF3: "ブランド体験", learnMore: "詳しく見る" },
  demo: { headline: "AIエージェントを体験", headlineAccent: "ライブ", subtitle: "Alex Rivera — AIカスタマーサクセススペシャリストをご紹介。音声またはチャットをお試しください。", voiceTitle: "Alexと話す", alexName: "Alex Rivera", alexRole: "AIカスタマーサクセススペシャリスト", speakersOn: "スピーカーON • クリックして接続", callAlex: "Alexに電話", ringing: "発信中...", connecting: "接続中", speaking: "話し中...", listening: "聞いています...", endCall: "通話終了", cancel: "キャンセル", poweredVoice: "デモはブラウザ音声合成を使用 • 本番環境はElevenLabs Expressive v3を使用", chatTitle: "Alexとチャット", chatPlaceholder: "Alexに何でも聞いてください...", chatHints: "試してみて：料金、医療、ROI、トライアル、迷っている、困っている、どのくらい、実績", chatGreeting: "こんにちは！VoiceFlow AIのAlexです。お越しいただきありがとうございます。今日はどのようにお手伝いできますか？" },
  pricing: { headline: "シンプルで", headlineAccent: "透明な料金", subtitle: "初期費用＋月額。隠れたコストなし。成長に合わせてスケール。", starter: "スターター", starterAudience: "小規模事業者", professional: "プロフェッショナル", professionalAudience: "成長中の企業", enterprise: "エンタープライズ", enterpriseAudience: "大規模組織・代理店", month: "/月", setupFee: "初期費用", customPricing: "カスタム設定・料金", mostPopular: "一番人気", getStarted: "始める", startTrial: "無料トライアル", contactSales: "営業に問い合わせ", f_chatbot1: "AIチャットボット1台", f_convos500: "月500会話", f_emailSupport: "メールサポート", f_basicAnalytics: "基本分析", f_voiceflow: "Voiceflow連携", f_lang1: "1言語", f_chatVoice: "AIチャットボット＋音声エージェント", f_convos2500: "月2,500会話", f_prioritySupport: "優先サポート", f_advancedAnalytics: "高度な分析", f_fullStack: "Voiceflow + Twilio + ElevenLabs", f_lang5: "5言語", f_crm: "CRM連携", f_leadQual: "リード評価", f_unlimitedAgents: "無制限エージェント", f_unlimitedConvos: "無制限会話", f_dedicatedManager: "専任アカウントマネージャー", f_customIntegrations: "カスタム連携", f_whiteLabel: "ホワイトラベルオプション", f_allLangs: "全言語対応", f_sla: "SLA保証", f_customTraining: "カスタムAIトレーニング" },
  caseStudies: { headline: "実際の企業による", headlineAccent: "実際の成果", subtitle: "AI搭載カスタマーサービスで数千ドルを節約している企業の事例をご覧ください。", challenge: "課題：", solution: "ソリューション：", med: { name: "MedFirst Clinic", industry: "医療", challenge: "3人チームが1日200件以上の患者電話に圧倒される", solution: "予約スケジューリングと患者トリアージ用AI音声エージェント", m1: "73%", m1l: "通話転換率", m2: "45%", m2l: "無断キャンセル減少", m3: "$12,400", m3l: "月間節約額", m4: "4.8/5", m4l: "患者満足度", quote: "VoiceFlow AIはフロントデスク業務を一変させました。患者は即時予約を気に入り、スタッフはようやく対面ケアに集中できるようになりました。", person: "Sarah Chen医師、医療ディレクター" }, apex: { name: "Apex Realty Group", industry: "不動産", challenge: "営業時間外のリードの60%をフォローアップなしで逃失", solution: "24時間リード評価用AIチャットボット＋音声エージェント", m1: "340%", m1l: "質の高いリード増加", m2: "28%", m2l: "迅速な応答", m3: "$31,000", m3l: "新規月間収益", m4: "89%", m4l: "リード獲得率", quote: "営業時間外の問い合わせのほとんどを逃していた状態から、ほぼすべてのリードを獲得できるようになりました。ROIは初月から明らかでした。", person: "Marcus Johnson、ブローカー/オーナー" }, shop: { name: "ShopWave", industry: "Eコマース", challenge: "平均8時間の応答時間が顧客を遠ざけている", solution: "注文、返品、商品質問を処理するAIチャットボット", m1: "2秒", m1l: "応答時間", m2: "82%", m2l: "自動解決", m3: "$18,700", m3l: "月間節約額", m4: "92%", m4l: "顧客満足度", quote: "お客様は以前、返信に何時間も待っていました。今では24時間、即座に正確なサポートを受けられます。サポートチケットは劇的に減少しました。", person: "Lisa Park、カスタマーエクスペリエンス責任者" } },
  roi: { headline: "あなたの", headlineAccent: "ROIを計算", subtitle: "VoiceFlow AIでどれだけ節約できるか正確にご確認ください。", tickets: "月間サポートチケット数", costPerTicket: "チケットあたりの平均コスト", agents: "現在のサポートエージェント数", salary: "エージェントの平均給与", yr: "/年", resultsTitle: "予想される節約額", currentCost: "現在の月間コスト", aiHandled: "AI処理割合", monthlySavings: "月間節約額", annualSavings: "年間節約額", paysItself: "投資回収期間", month_one: "ヶ月", months: "ヶ月", getQuote: "カスタム見積もりを取得" },
  dashboard: { headline: "あなたの", headlineAccent: "コマンドセンター", subtitle: "すべての会話を監視し、パフォーマンスを追跡し、AIエージェントを一つのダッシュボードから最適化。", title: "VoiceFlow AIダッシュボード", overview: "概要", conversations: "会話", agentsNav: "エージェント", analytics: "分析", settings: "設定", totalConvos: "総会話数", resolutionRate: "解決率", avgResponse: "平均応答時間", customerSat: "顧客満足度", chartTitle: "会話ボリューム（7日間）", recentTitle: "最近の会話", resolved: "解決済み", inProgress: "進行中", escalated: "エスカレーション", getAccess: "ダッシュボードの完全アクセスを取得" },
  quote: { headline: "あなたの", headlineAccent: "AI即時見積もり", subtitle: "いくつかの質問に答えるだけで、AIが最適なソリューションを提案します。", step1: "あなたの業界は？", step2: "月間のカスタマーインタラクション数は？", step3: "必要なチャネルは？", step4: "もう少しです！あなたについて教えてください。", vol1: "500未満", vol2: "500 - 2,000", vol3: "2,000 - 5,000", vol4: "5,000+", chWebsite: "ウェブサイトチャット", chPhone: "電話/音声", chSMS: "SMS", chWhatsApp: "WhatsApp", chSocial: "ソーシャルメディア", nameField: "氏名", emailField: "メールアドレス", phoneField: "電話番号", companyField: "会社名", back: "戻る", next: "次へ", getMyQuote: "見積もりを取得", quoteReady: "お見積もりの準備ができました！", basedOn: "ご回答に基づき、おすすめは：", plan: "プラン", forIndustry: "対象", withVolume: "月間", monthlyInteractions: "インタラクション", estSavings: "推定月間節約額", specialistContact: "2時間以内にスペシャリストがご連絡いたします：", other: "その他" },
  footer: { tagline: "眠らないAI搭載カスタマーサービス。", solutions: "ソリューション", company: "会社情報", resources: "リソース", about: "会社概要", careers: "採用情報", blog: "ブログ", contact: "お問い合わせ", partners: "パートナー", docs: "ドキュメント", apiRef: "APIリファレンス", status: "ステータスページ", privacy: "プライバシーポリシー", terms: "利用規約", copyright: "© 2024 VoiceFlow AI. All rights reserved.", builtWith: "Voiceflow + ElevenLabs + Twilioで構築" },
  langName: "日本語",
};

export default ja;
