import type { TranslationKeys } from "./translations";

const ko: TranslationKeys = {
  nav: { solutions: "솔루션", demo: "데모", pricing: "가격", caseStudies: "성공 사례", roiCalculator: "ROI 계산기", dashboard: "대시보드", tryDemo: "데모 체험" },
  hero: { badge: "GPT-4 + ElevenLabs 음성 AI 탑재", headline1: "지원 비용 70% 절감", headline2: "실제로 대화하는 AI로", subtitle: "맞춤형 AI 챗봇과 음성 에이전트가 고객 서비스, 리드 검증, 예약 관리를 24시간 처리합니다. Voiceflow, ElevenLabs, Twilio로 구축.", ctaVoice: "음성 데모 체험", ctaRoi: "ROI 계산하기", statBusinesses: "서비스 기업", statCost: "비용 절감", statAvailability: "가용성", statResponse: "응답 시간" },
  trust: { headline: "전 세계 500개 이상의 기업이 신뢰합니다", soc2: "SOC 2 준수", uptime: "99.9% 가동 SLA", hipaa: "HIPAA 대응" },
  solutions: { headline: "AI 솔루션", headlineAccent: "산업별", subtitle: "산업별 전문 지식과 워크플로우에 특화된 AI 에이전트.", healthcare: "의료", healthcareDesc: "HIPAA 준수를 유지하면서 환자 상호작용을 자동화합니다.", healthcareF1: "예약 스케줄링", healthcareF2: "환자 분류", healthcareF3: "보험 확인", realEstate: "부동산", realEstateDesc: "모든 리드를 확보하고 24시간 방문 일정을 잡습니다.", realEstateF1: "리드 검증", realEstateF2: "매물 정보", realEstateF3: "방문 스케줄링", ecommerce: "이커머스", ecommerceDesc: "만족도를 높이고 반품을 줄이는 즉시 지원.", ecommerceF1: "주문 추적", ecommerceF2: "반품 처리", ecommerceF3: "제품 추천", legal: "법률", legalDesc: "고객 접수를 간소화하고 일반적인 질문에 즉시 답변합니다.", legalF1: "접수 양식", legalF2: "상담 예약", legalF3: "FAQ 처리", homeServices: "홈 서비스", homeServicesDesc: "서비스 콜이나 긴급 출동을 다시는 놓치지 마세요.", homeServicesF1: "예약 관리", homeServicesF2: "즉시 견적", homeServicesF3: "긴급 출동", agencies: "에이전시", agenciesDesc: "각 클라이언트를 위한 맞춤 화이트라벨 AI 에이전트.", agenciesF1: "화이트라벨 솔루션", agenciesF2: "멀티클라이언트 대시보드", agenciesF3: "브랜드 경험", learnMore: "자세히 보기" },
  demo: { headline: "AI 에이전트 체험", headlineAccent: "라이브", subtitle: "Alex Rivera를 만나보세요 — AI 고객 성공 전문가. 음성 또는 채팅을 시도하세요.", voiceTitle: "Alex와 통화", alexName: "Alex Rivera", alexRole: "AI 고객 성공 전문가", speakersOn: "스피커 켜짐 • 클릭하여 연결", callAlex: "Alex에게 전화", ringing: "발신 중...", connecting: "연결 중", speaking: "말하는 중...", listening: "듣는 중...", endCall: "통화 종료", cancel: "취소", poweredVoice: "데모는 브라우저 음성 합성 사용 • 프로덕션은 ElevenLabs Expressive v3 사용", chatTitle: "Alex와 채팅", chatPlaceholder: "Alex에게 무엇이든 물어보세요...", chatHints: "시도해 보세요: 가격, 의료, ROI, 체험, 잘 모르겠어요, 불만, 얼마나, 성과", chatGreeting: "안녕하세요! VoiceFlow AI의 Alex입니다. 방문해 주셔서 정말 기쁩니다. 오늘 어떻게 도와드릴까요?" },
  pricing: { headline: "간단하고", headlineAccent: "투명한 가격", subtitle: "설정비 + 월비. 숨겨진 비용 없음. 성장에 맞춰 확장.", starter: "스타터", starterAudience: "소규모 비즈니스", professional: "프로페셔널", professionalAudience: "성장하는 비즈니스", enterprise: "엔터프라이즈", enterpriseAudience: "대기업 및 에이전시", month: "/월", setupFee: "설정비", customPricing: "맞춤 설정 및 가격", mostPopular: "가장 인기", getStarted: "시작하기", startTrial: "무료 체험", contactSales: "영업팀 연락", f_chatbot1: "AI 챗봇 1개", f_convos500: "월 500회 대화", f_emailSupport: "이메일 지원", f_basicAnalytics: "기본 분석", f_voiceflow: "Voiceflow 연동", f_lang1: "1개 언어", f_chatVoice: "AI 챗봇 + 음성 에이전트", f_convos2500: "월 2,500회 대화", f_prioritySupport: "우선 지원", f_advancedAnalytics: "고급 분석", f_fullStack: "Voiceflow + Twilio + ElevenLabs", f_lang5: "5개 언어", f_crm: "CRM 연동", f_leadQual: "리드 검증", f_unlimitedAgents: "무제한 에이전트", f_unlimitedConvos: "무제한 대화", f_dedicatedManager: "전담 계정 매니저", f_customIntegrations: "맞춤 연동", f_whiteLabel: "화이트라벨 옵션", f_allLangs: "전체 언어", f_sla: "SLA 보장", f_customTraining: "맞춤 AI 트레이닝" },
  caseStudies: { headline: "실제 기업의", headlineAccent: "실제 성과", subtitle: "AI 기반 고객 서비스로 수천 달러를 절약하는 기업들의 사례를 확인하세요.", challenge: "과제:", solution: "솔루션:", med: { name: "MedFirst 클리닉", industry: "의료", challenge: "3명의 팀이 하루 200건 이상의 환자 전화에 압도됨", solution: "예약 스케줄링 및 환자 분류를 위한 AI 음성 에이전트", m1: "73%", m1l: "통화 전환율", m2: "45%", m2l: "노쇼 감소", m3: "$12,400", m3l: "월간 절약", m4: "4.8/5", m4l: "환자 만족도", quote: "VoiceFlow AI가 프론트 데스크 운영을 완전히 바꿔놓았습니다. 환자들은 즉시 예약을 좋아하고, 직원들은 드디어 대면 진료에 집중할 수 있게 되었습니다.", person: "Sarah Chen 박사, 의료 디렉터" }, apex: { name: "Apex 부동산 그룹", industry: "부동산", challenge: "영업시간 외 리드의 60%를 추적 시스템 없이 놓침", solution: "24/7 리드 검증을 위한 AI 챗봇 + 음성 에이전트", m1: "340%", m1l: "더 많은 검증된 리드", m2: "28%", m2l: "더 빠른 응답", m3: "$31,000", m3l: "신규 월 수익", m4: "89%", m4l: "리드 확보율", quote: "영업시간 외 문의의 대부분을 놓치던 것에서 거의 모든 리드를 확보하게 되었습니다. ROI는 첫 달부터 명확했습니다.", person: "Marcus Johnson, 중개인/대표" }, shop: { name: "ShopWave", industry: "이커머스", challenge: "평균 8시간 응답 시간으로 고객 이탈", solution: "주문, 반품, 제품 문의를 처리하는 AI 챗봇", m1: "2초", m1l: "응답 시간", m2: "82%", m2l: "자동 해결", m3: "$18,700", m3l: "월간 절약", m4: "92%", m4l: "고객 만족도", quote: "고객들은 이전에 답변을 받기까지 몇 시간을 기다려야 했습니다. 이제는 24시간 즉각적이고 정확한 도움을 받습니다. 지원 티켓이 극적으로 줄었습니다.", person: "Lisa Park, 고객 경험 책임자" } },
  roi: { headline: "당신의", headlineAccent: "ROI 계산", subtitle: "VoiceFlow AI로 얼마나 절약할 수 있는지 정확히 확인하세요.", tickets: "월간 지원 티켓", costPerTicket: "티켓당 평균 비용", agents: "현재 지원 에이전트", salary: "에이전트 평균 급여", yr: "/년", resultsTitle: "예상 절약액", currentCost: "현재 월간 비용", aiHandled: "AI 처리 비율", monthlySavings: "월간 절약", annualSavings: "연간 절약", paysItself: "투자 회수 기간", month_one: "개월", months: "개월", getQuote: "맞춤 견적 받기" },
  dashboard: { headline: "당신의", headlineAccent: "커맨드 센터", subtitle: "하나의 대시보드에서 모든 대화를 모니터링하고, 성과를 추적하며, AI 에이전트를 최적화하세요.", title: "VoiceFlow AI 대시보드", overview: "개요", conversations: "대화", agentsNav: "에이전트", analytics: "분석", settings: "설정", totalConvos: "총 대화 수", resolutionRate: "해결률", avgResponse: "평균 응답 시간", customerSat: "고객 만족도", chartTitle: "대화 볼륨 (7일)", recentTitle: "최근 대화", resolved: "해결됨", inProgress: "진행 중", escalated: "에스컬레이션", getAccess: "전체 대시보드 액세스 받기" },
  quote: { headline: "당신의", headlineAccent: "AI 즉시 견적", subtitle: "몇 가지 질문에 답하면 AI가 완벽한 솔루션을 추천합니다.", step1: "어떤 산업에 계신가요?", step2: "월간 고객 상호작용 수는?", step3: "어떤 채널이 필요하신가요?", step4: "거의 다 됐어요! 자신에 대해 알려주세요.", vol1: "500 미만", vol2: "500 - 2,000", vol3: "2,000 - 5,000", vol4: "5,000+", chWebsite: "웹사이트 채팅", chPhone: "전화/음성", chSMS: "SMS", chWhatsApp: "WhatsApp", chSocial: "소셜 미디어", nameField: "성명", emailField: "이메일 주소", phoneField: "전화번호", companyField: "회사명", back: "뒤로", next: "다음", getMyQuote: "견적 받기", quoteReady: "견적이 준비되었습니다!", basedOn: "답변을 기반으로 추천드립니다:", plan: "플랜", forIndustry: "대상", withVolume: "월", monthlyInteractions: "회 상호작용", estSavings: "예상 월간 절약액", specialistContact: "2시간 내에 전문가가 연락드립니다:", other: "기타" },
  footer: { tagline: "절대 쉬지 않는 AI 고객 서비스.", solutions: "솔루션", company: "회사", resources: "리소스", about: "소개", careers: "채용", blog: "블로그", contact: "문의", partners: "파트너", docs: "문서", apiRef: "API 레퍼런스", status: "서비스 상태", privacy: "개인정보 처리방침", terms: "이용약관", copyright: "© 2024 VoiceFlow AI. All rights reserved.", builtWith: "Voiceflow + ElevenLabs + Twilio로 구축" },
  langName: "한국어",
};

export default ko;
