import type { TranslationKeys } from "./translations";

const zh: TranslationKeys = {
  nav: { solutions: "解决方案", demo: "演示", pricing: "价格", caseStudies: "成功案例", roiCalculator: "ROI计算器", dashboard: "控制面板", tryDemo: "试用演示" },
  hero: { badge: "由GPT-4 + ElevenLabs语音AI驱动", headline1: "降低70%支持成本", headline2: "用真正会说话的AI", subtitle: "定制AI聊天机器人和语音代理，处理客户服务、筛选潜在客户并预约——全天候24/7。基于Voiceflow、ElevenLabs和Twilio构建。", ctaVoice: "试用语音演示", ctaRoi: "计算您的ROI", statBusinesses: "服务企业", statCost: "成本降低", statAvailability: "可用性", statResponse: "响应时间" },
  trust: { headline: "全球500+企业信赖之选", soc2: "SOC 2合规", uptime: "99.9%正常运行SLA", hipaa: "HIPAA就绪" },
  solutions: { headline: "AI解决方案", headlineAccent: "按行业", subtitle: "基于行业特定知识和工作流程定制的AI代理。", healthcare: "医疗健康", healthcareDesc: "在保持HIPAA合规的同时自动化患者互动。", healthcareF1: "预约安排", healthcareF2: "患者分诊", healthcareF3: "保险验证", realEstate: "房地产", realEstateDesc: "全天候捕获每个潜在客户并安排看房。", realEstateF1: "潜客筛选", realEstateF2: "房产信息", realEstateF3: "看房安排", ecommerce: "电子商务", ecommerceDesc: "即时支持提升满意度并减少退货。", ecommerceF1: "订单追踪", ecommerceF2: "退货处理", ecommerceF3: "产品推荐", legal: "法律", legalDesc: "简化客户接待并即时回答常见问题。", legalF1: "接待表格", legalF2: "咨询预约", legalF3: "常见问题处理", homeServices: "家庭服务", homeServicesDesc: "不再错过任何服务电话或紧急调度。", homeServicesF1: "预约管理", homeServicesF2: "即时报价", homeServicesF3: "紧急调度", agencies: "代理机构", agenciesDesc: "为每个客户定制品牌的白标AI代理。", agenciesF1: "白标解决方案", agenciesF2: "多客户仪表板", agenciesF3: "品牌化体验", learnMore: "了解更多" },
  demo: { headline: "体验AI代理", headlineAccent: "实时", subtitle: "认识Alex Rivera——您的AI客户成功专家。试用语音或聊天。", voiceTitle: "与Alex对话", alexName: "Alex Rivera", alexRole: "AI客户成功专家", speakersOn: "扬声器已开启 • 点击连接", callAlex: "呼叫Alex", ringing: "拨号中...", connecting: "正在连接", speaking: "正在说话...", listening: "正在聆听...", endCall: "结束通话", cancel: "取消", poweredVoice: "演示使用浏览器语音合成 • 生产环境使用ElevenLabs Expressive v3", chatTitle: "与Alex聊天", chatPlaceholder: "向Alex提问...", chatHints: "试试：价格、医疗、ROI、试用、不确定、困扰、多长时间、效果", chatGreeting: "您好！我是VoiceFlow AI的Alex。很高兴您的到来。今天我能帮您什么？" },
  pricing: { headline: "简单", headlineAccent: "透明的价格", subtitle: "设置费+月费。无隐藏成本。按需扩展。", starter: "入门版", starterAudience: "小型企业", professional: "专业版", professionalAudience: "成长型企业", enterprise: "企业版", enterpriseAudience: "大型组织和代理机构", month: "/月", setupFee: "设置费", customPricing: "定制设置和价格", mostPopular: "最受欢迎", getStarted: "开始使用", startTrial: "免费试用", contactSales: "联系销售", f_chatbot1: "1个AI聊天机器人", f_convos500: "每月500次对话", f_emailSupport: "邮件支持", f_basicAnalytics: "基础分析", f_voiceflow: "Voiceflow集成", f_lang1: "1种语言", f_chatVoice: "AI聊天机器人+语音代理", f_convos2500: "每月2,500次对话", f_prioritySupport: "优先支持", f_advancedAnalytics: "高级分析", f_fullStack: "Voiceflow + Twilio + ElevenLabs", f_lang5: "5种语言", f_crm: "CRM集成", f_leadQual: "潜客筛选", f_unlimitedAgents: "无限代理", f_unlimitedConvos: "无限对话", f_dedicatedManager: "专属客户经理", f_customIntegrations: "定制集成", f_whiteLabel: "白标选项", f_allLangs: "所有语言", f_sla: "SLA保证", f_customTraining: "定制AI培训" },
  caseStudies: { headline: "来自真实企业的", headlineAccent: "真实成果", subtitle: "了解像您一样的企业如何通过AI客服节省数千美元。", challenge: "挑战：", solution: "解决方案：", med: { name: "MedFirst诊所", industry: "医疗健康", challenge: "每天200+患者来电让3人团队不堪重负", solution: "用于预约安排和患者分诊的AI语音代理", m1: "73%", m1l: "来电转化率", m2: "45%", m2l: "减少爽约", m3: "$12,400", m3l: "每月节省", m4: "4.8/5", m4l: "患者满意度", quote: "VoiceFlow AI彻底改变了我们的前台运营。患者喜欢即时预约，我们的员工终于可以专注于当面护理。", person: "Sarah Chen博士，医疗总监" }, apex: { name: "Apex房地产集团", industry: "房地产", challenge: "下班后60%的潜在客户流失，无跟进系统", solution: "AI聊天机器人+语音代理实现24/7潜客筛选", m1: "340%", m1l: "更多合格潜客", m2: "28%", m2l: "更快响应", m3: "$31,000", m3l: "新增月收入", m4: "89%", m4l: "潜客捕获率", quote: "我们从错过大部分下班后的咨询变为几乎捕获每一个潜在客户。ROI在第一个月就显而易见。", person: "Marcus Johnson，经纪人/业主" }, shop: { name: "ShopWave", industry: "电子商务", challenge: "平均8小时响应时间导致客户流失", solution: "AI聊天机器人处理订单、退货和产品咨询", m1: "2秒", m1l: "响应时间", m2: "82%", m2l: "自动解决", m3: "$18,700", m3l: "每月节省", m4: "92%", m4l: "客户满意度", quote: "我们的客户过去要等几个小时才能得到回复。现在他们全天候获得即时、准确的帮助。支持工单大幅下降。", person: "Lisa Park，客户体验主管" } },
  roi: { headline: "计算您的", headlineAccent: "ROI", subtitle: "精确了解您使用VoiceFlow AI可以节省多少。", tickets: "每月支持工单", costPerTicket: "每张工单平均成本", agents: "当前支持代理数", salary: "代理平均薪资", yr: "/年", resultsTitle: "您的预计节省", currentCost: "当前每月成本", aiHandled: "AI处理百分比", monthlySavings: "每月节省", annualSavings: "每年节省", paysItself: "投资回收期", month_one: "个月", months: "个月", getQuote: "获取定制报价" },
  dashboard: { headline: "您的", headlineAccent: "指挥中心", subtitle: "从一个仪表板监控每次对话、跟踪性能并优化AI代理。", title: "VoiceFlow AI仪表板", overview: "概览", conversations: "对话", agentsNav: "代理", analytics: "分析", settings: "设置", totalConvos: "总对话数", resolutionRate: "解决率", avgResponse: "平均响应时间", customerSat: "客户满意度", chartTitle: "对话量（7天）", recentTitle: "最近对话", resolved: "已解决", inProgress: "进行中", escalated: "已升级", getAccess: "获取完整仪表板访问权限" },
  quote: { headline: "获取您的", headlineAccent: "AI即时报价", subtitle: "回答几个问题，我们的AI将为您推荐完美方案。", step1: "您的行业是？", step2: "每月客户互动次数？", step3: "您需要哪些渠道？", step4: "快完成了！告诉我们关于您的信息。", vol1: "500以下", vol2: "500 - 2,000", vol3: "2,000 - 5,000", vol4: "5,000+", chWebsite: "网站聊天", chPhone: "电话/语音", chSMS: "短信", chWhatsApp: "WhatsApp", chSocial: "社交媒体", nameField: "姓名", emailField: "电子邮箱", phoneField: "电话号码", companyField: "公司名称", back: "返回", next: "下一步", getMyQuote: "获取报价", quoteReady: "您的报价已准备好！", basedOn: "根据您的回答，我们推荐：", plan: "方案", forIndustry: "适用于", withVolume: "月", monthlyInteractions: "次互动", estSavings: "预计每月节省", specialistContact: "专家将在2小时内通过以下方式联系您：", other: "其他" },
  footer: { tagline: "永不休息的AI客户服务。", solutions: "解决方案", company: "公司", resources: "资源", about: "关于我们", careers: "招聘", blog: "博客", contact: "联系我们", partners: "合作伙伴", docs: "文档", apiRef: "API参考", status: "服务状态", privacy: "隐私政策", terms: "服务条款", copyright: "© 2024 VoiceFlow AI. 保留所有权利。", builtWith: "基于 Voiceflow + ElevenLabs + Twilio 构建" },
  langName: "中文",
};

export default zh;
